name: build & deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Install and Build
      run: |
        npm install
        npm run docs:build
        
    - name: Deploy Build Files
      run: |
        cd .vuepress/dist
        git config --global user.email "rudgns517@naver.com"
        git config --global user.name "dobycode"
        git init
        git add -A
        git commit -m 'deploy with vuepress'
        git push -f https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }} HEAD:gh-pages
